#!/bin/bash

FILES=`ls intermediate/*.txt`

rm -rf html
mkdir html

for f in $FILES
do
    echo "Processing $f"
    NAME=`echo $f | sed 's/\(.*\)\..*/\1/'`
    markdown_py $f > $NAME.html
done

mv intermediate/*.html html/
