#!/bin/bash

# PotBliki, Plain Text Bliki Tools.
# Copyright (C) 2011  Daniel Hjort
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

EXPECTED_ARGS=1
E_BADARGS=65

if [ $# -ne $EXPECTED_ARGS ]
then
  echo "usage: install [INSTALL_PATH]"
  exit $E_BADARGS
fi

if [ ! -d $1 ]
then
  echo "Target path doesn't exist."
  exit $E_BADARGS
fi

chmod u+x potbliki
cp potbliki $1
cp potbliki_util $1

if [ ! -d $1/.potbliki ]
then
  mkdir $1/.potbliki
fi
cp templates/disqus-template.html $1/.potbliki
cp templates/html-head-template.html $1/.potbliki
cp push.cgi $1/.potbliki

cat <<EOF > $1/.potbliki/potbliki_env
POTBLIKI_USER_HOME=$HOME
EOF


DEP=`which sundown`

if [ "$DEP" == '' ]
then
  echo "Installing sundown..."
  current_dir=`pwd`
  cd lib/sundown
  make
  chmod 755 sundown
  cp sundown $1
  cd $current_dir
fi
