#!/bin/bash

EXPECTED_ARGS=1
E_BADARGS=65

if [ $# -ne $EXPECTED_ARGS ]
then
  echo "usage: install [INSTALL_PATH]"
  exit $E_BADARGS
fi

if [ ! -d $1 ]
then
  echo "Target path doesn't exist."
  exit $E_BADARGS
fi

chmod u+x potbliki
cp potbliki $1
ORIG_DIR=`pwd`
cd lib/python_markdown/
python setup.py install
cd $ORIG_DIR
cp lib/python_markdown/bin/markdown_py $1

