#!/bin/bash

# Find CamelCase words by reg exp and replace with Markdown link [word](word.html)

rm -rf intermediate
mkdir intermediate

FILES=`ls *.txt`

for f in $FILES
do
	echo "Processing $f"
	sed -E 's/([A-Z][a-z]*)+[A-Z][a-z]+([A-Z][a-z]*)*/[&](&.html)/' <$f >intermediate/$f
	cp $f intermediate/$f
done
