#! /bin/sh

# PotBliki, Plain Text Bliki Tools.
# Copyright (C) 2011  Daniel Hjort
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

function markdown_wikiwords_in_file
{

  SED_FLAG=""

  if [ "$SYSTEM" == 'Darwin' ]
  then
    SED_FLAG="-E"
  fi

# Find CamelCase words by reg exp and replace with Markdown link [word](word.html)

  file=$1

  echo "Processing $file"
  perl -pe 's/(?<!~)([A-Z][a-z]*)+[A-Z][a-z]+([A-Z][a-z]*)*/[$&]($&.html)/g' <$file >${file}_
  perl -pe 's/(?<!~)~//g' <${file}_ >$file
  rm ${file}_

}

