#!/bin/bash

# Generates a Markdown formated IndexPage.txt from all txt-files.

FILES=`ls *.txt`

echo "$1"
echo "========="
echo "----"

echo ""
echo "Posts"
echo "-----"
echo ""

# Find all files with post header and print filename - date (sorted by date)

for f in $FILES
do
    FIRST_WORD=`head -n 1 $f | awk '{print $1}'`
    DATE=`head -n 4 $f | sed -n 3p | awk '{print $2}'`
    [ "$FIRST_WORD" == 'title:' ] && ( echo "* $DATE - $f" | sed 's/\(.*\)\..*/\1/')
done


echo ""
echo "Wiki"
echo "----"
echo ""

# For the rest in alphabetical order echo filename

for f in $FILES
do
    echo $f | sed 's/\(.*\)\..*/\1/'
done

echo ""
echo "----"
